name: CI
on:
  push:
    branches: ['dev', 'renovate/*']
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: yarn
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: nandenjin/gmail-to-slack
